Repository codestates-seb/seb44_main_029, pull requests merged in 2023-08, with the labels that each got.

#152 [FE] Feat: redux
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/header/Nav.tsx
  client/src/components/main/TitleOne.tsx
  client/src/components/main/TitleThree.tsx
  client/src/components/theme/themeDetailedItem/DetailedItem.tsx
  client/src/components/theme/themeItemList/ItemList.tsx
  client/src/feature/header/modalSlice.ts
  client/src/feature/header/navSlice.ts
  client/src/hooks/useShowLoginForm.ts
  client/src/index.tsx
  client/src/pages/ThemeItemList.tsx
  client/src/store.ts
Labels: frontend 📱, refactor ⚙️, feature ✨

#153 [FE] Refactor: 프로필 페이지 리덕스로 변경
  client/src/components/profile/edit/EditImg.tsx
  client/src/components/profile/edit/EditName.tsx
  client/src/components/profile/edit/EditProfile.tsx
  client/src/components/profile/like/Card.tsx
  client/src/components/profile/like/LikeList.tsx
  client/src/components/profile/user/ChangeProfile.tsx
  client/src/feature/profile/editSlice.ts
  client/src/pages/Profile.tsx
  client/src/store.ts
Labels: frontend 📱, refactor ⚙️

#154 Feat: nav 개선
  client/src/components/header/AudioPlayer.tsx
  client/src/components/header/Header.tsx
  client/src/components/header/Nav.tsx
  client/src/components/header/Nav2.tsx
  client/src/components/theme/themeList/ThemeCarousel.tsx
  client/src/components/theme/themeList/TimerModal.tsx
Labels: frontend 📱, refactor ⚙️

#155 [FE] Refactor 로그인 훅 생성 및 sweetalert 적용
  client/package-lock.json
  client/package.json
  client/src/components/Login/GuestLoginButton.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/header/Nav.tsx
  client/src/components/profile/user/ChangeProfile.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/hooks/login/useLogin.ts
Labels: frontend 📱, refactor ⚙️, feature ✨

#156 Feat: carousel
  client/package-lock.json
  client/package.json
  client/src/components/header/AudioPlayer.tsx
  client/src/components/header/Nav2.tsx
  client/src/components/theme/themeList/Carousel.tsx
  client/src/components/theme/themeList/CarouselArrowsButton.tsx
  client/src/components/theme/themeList/imageByIndex.ts
  client/src/pages/ThemeList.tsx
Labels: frontend 📱, feature ✨
